substitutions:
  name: cabinet-ac
  friendly_name: Cabinet Climate
  # Wi-Fi AP password in safe mode. Default: "12345678"
  #ap_password: !secret ap_password
  # Network domain. Default: .local
  #domain: !secret domain
  # HomeAssistant API key. Default: sOsBobs9D/bNFOBZ5GFr+TuHdMbYMntmDNXt5F/3lk0=
  #api_key: !secret api_key
  # OTA firmware update password. Default: no password
  #ota_password: !secret ota_password

wifi:
  # Your SSID name. Must be located in 'secrets.yaml' file.
  ssid: !secret wifi_ssid
  # Your SSID password. Must be located in 'secrets.yaml' file.
  password: !secret wifi_password
  # Uncomment on the first firmware update.
  #use_address: iot-uni-dongle.local

esphome:
  project:
    name: "dudanov.midea-ac-control"
    version: "1.0"

packages:
  remote_package:
    url: https://github.com/dudanov/esphome-packages
    refresh: 0d
    files: [
        # Main dongle package
        hardware/iot-uni-dongle/device.yaml,
        # Generic GREE. Select your model HERE.
        climate/gree/generic.yaml,
      ]
