substitutions:
  buzzer_pin: GPIO25

esphome:
  project:
    name: 'dudanov.airsensor-irtransmitter'
    version: '1.0'
  on_boot:
    then:
      - rtttl.play: 'scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b'

packages:
  esp32: !include esp32/esp32.yaml
  default: !include ../common/default.yaml
  web: !include ../common/web.yaml
  buzzer: !include ../common/buzzer/esp32.yaml

uart:
  rx_pin: GPIO19
  tx_pin: GPIO18
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: mhz19_device
    co2:
      id: mhz19_co2_sensor
      name: CO2
    temperature:
      id: mhz19_temperature_sensor
    update_interval: 60s
    automatic_baseline_calibration: false
  - platform: dht
    pin: GPIO14
    model: AM2302
    temperature:
      id: am2302_temperature_sensor
      name: Temperature
    humidity:
      id: am2302_humidity_sensor
      name: Humidity
    update_interval: 60s

remote_transmitter:
  pin: GPIO23
  carrier_duty_percent: 50%

button:
  - platform: template
    id: tv_button
    name: TV
    icon: mdi:television-box
    on_press:
      # Android TVBox Power Command
      - remote_transmitter.transmit_nec:
          address: 0x7F80
          command: 0xAE51
      - delay: 200ms
        # Samsung TV Power Command
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO4

microphone:
  - platform: i2s_audio
    # ICS-43434
    # https://invensense.tdk.com/wp-content/uploads/2016/02/DS-000069-ICS-43434-v1.2.pdf
    id: mic_id
    channel: left
    bits_per_sample: 32bit
    adc_type: external
    pdm: false
    i2s_din_pin: GPIO2

voice_assistant:
  microphone: mic_id
