# Default names
substitutions:
  name: esphome-device
  friendly_name: ESPHome Device
  domain: ".local"

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  domain: ${domain}

# Default device packages
packages:
  # Main template
  main: !include main.yaml
  # Web server
  #web: !include web.yaml
  # Restart button
  restart: !include restart.yaml
  # Safe Mode button
  #safe-mode: !include safe-mode.yaml
  # Shutdown button
  #shutdown: !include shutdown.yaml
  # Uptime text sensor
  uptime: !include uptime.yaml
  # WiFi Sensors
  wifi: !include wifi.yaml
  # ESPHome version
  #version: !include version.yaml
