# Default device packages
packages:
  # Main template
  main: !include main.yaml
  # Home Assistant API
  api: !include api.yaml
  # Restart button
  restart: !include restart.yaml
  # Uptime text sensor
  uptime: !include uptime.yaml
  # WiFi Sensors
  wifi: !include wifi.yaml
  # ESPHome version with timestamp
  version: !include version.yaml