substitutions:
  domain: ".local"
  ap_password: "12345678"
  ota_password: "8940a295270cef3d1e420838161bb145"
  api_key: "sOsBobs9D/bNFOBZ5GFr+TuHdMbYMntmDNXt5F/3lk0="

# Default config
esphome:
  name: ${name}
  platformio_options:
    upload_speed: 2000000

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}

# Enable logger with DEBUG level
logger:

# Enable OTA
ota:
  password: ${ota_password}

# Enable WiFi default access point
wifi:
  domain: ${domain}
  ap:
    password: ${ap_password}
