# Default config
esphome:
  name: ${name}
  platformio_options:
    upload_speed: 2000000

# Enable Home Assistant API
api:

# Enable logger with DEBUG level
logger:

# Enable OTA
ota:

# Enable WiFi default access point
wifi:
  ap:
    password: "12345678"
