substitutions:
  name: esphome-device
  friendly_name: ESPHome Device
  domain: ".local"
  api_key: "sOsBobs9D/bNFOBZ5GFr+TuHdMbYMntmDNXt5F/3lk0="
  ap_password: "12345678"
  ota_password: ""

# Default config
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  platformio_options:
    upload_speed: 2000000

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}

# Enable logger with DEBUG level
logger:

# Enable OTA
ota:
  password: ${ota_password}

# Enable WiFi default access point
wifi:
  domain: ${domain}
  ap:
    password: ${ap_password}
