substitutions:
  framework: arduino

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: ${framework}

esphome:
  platformio_options:
    build_unflags: -D ARDUINO_USB_MODE
    build_flags: -D ARDUINO_USB_MODE=0 -D ARDUINO_USB_CDC_ON_BOOT=0
