# Minimal iot-uni-dongle config
substitutions:
  name: iot-uni-dongle

packages:
  # Common minimal config
  main: !include ../../common/main.yaml
  # ESP-12E module minimal config
  esp8266: !include ../esp12e/esp8266.yaml