# Minimal iot-uni-dongle config
substitutions:
  name: iot-uni-dongle

packages:
  main: !include ../../common/main.yaml
  esp8266: !include ../../common/esp8266.yaml
  web: !include ../../common/web.yaml

# Disable logging via UART
logger:
  baud_rate: 0

# UART config
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
