# Minimal iot-uni-dongle config
substitutions:
  name: iot-uni-dongle

packages:
  # ESP-12E module minimal config
  esp8266: !include ../esp12e/esp8266.yaml
  # Common minimal config
  minimal: !include ../../common/minimal.yaml
