# Default names
substitutions:
  name: light-controller
  friendly_name: Light Controller

esphome:
  project:
    name: "dudanov.light-controller"
    version: "1.0"

packages:
  default: !include ../../common/default.yaml
  esp32: !include ../../common/esp32.yaml
