# Default names
substitutions:
  name: hall-light
  friendly_name: Hall Light

esphome:
  project:
    name: "dudanov.light-controller"
    version: "1.0"
  includes:
    - feron_light.h

packages:
  default: !include ../../common/default.yaml
  esp32: !include ../../common/esp32.yaml

remote_transmitter:
  id: ir_remote
  pin: GPIO25
  carrier_duty_percent: 100%

light:
  - platform: custom
    lambda: |-
      auto light = new FeronLightOutput();
      light->set_remote_transmitter(id(ir_remote));
      return {light};
    lights:
      name: "${friendly_name} Feron"
      id: cabinet_light
      default_transition_length: 0s
      gamma_correct: 1.0
