# This light for my project: https://github.com/dudanov/feron-light-advanced-control
# feron_light.h must be copied in HASS /config/esphome folder

esphome:
  includes:
    - feron_light.h

light:
  - platform: custom
    lambda: |-
      auto light = new FeronLightOutput();
      light->set_remote_transmitter(id(ir_remote));
      light->set_fade_switch(id(fade_switch));
      return {light};
    lights:
      name: Feron
      id: cabinet_light
      default_transition_length: 0s
      gamma_correct: 1.0

switch:
  - platform: template
    id: fade_switch
    name: Feron Fade Effect
    icon: mdi:animation-play-outline
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

remote_transmitter:
  id: ir_remote
  pin: GPIO25
  carrier_duty_percent: 100%

api:
  services:
    - service: feron_preset_load
      # Load specified preset from internal EEPROM
      variables:
        preset: int
      then:
        - lambda: |-
            FeronLightOutput::preset_load(id(ir_remote), preset, !id(fade_switch).state);
    - service: feron_preset_save
      # Save current state as specified preset to internal EEPROM
      variables:
        preset: int
      then:
        - lambda: |-
            FeronLightOutput::preset_save(id(ir_remote), preset);
