# Default names
substitutions:
  name: my-switch
  friendly_name: My Switch
  buzzer_pin: GPIO4

esphome:
  project:
    name: "dudanov.legrand-switch"
    version: "1.0"

packages:
  default: !include ../../common/default.yaml
  esp32: !include ../../common/esp32.yaml
  buzzer: !include ../../common/buzzer/esp32.yaml

# Onboard status led
status_led:
  pin: GPIO32

# Adds two main switch keys
binary_sensor:
  - platform: gpio
    name: Key 1
    icon: mdi:electric-switch
    id: key1
    pin:
      number: GPIO0
      inverted: true
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: Key 2
    icon: mdi:electric-switch
    id: key2
    pin:
      number: GPIO33
      inverted: true
    filters:
      - delayed_on_off: 50ms
