# Default names
substitutions:
  name: my-switch
  friendly_name: My Switch
  buzzer_pin: GPIO4

# Onboard status led
status_led:
  pin: GPIO32

# Adds two main switch keys
binary_sensor:
  - platform: gpio
    name: "${friendly_name} Key 1"
    icon: mdi:electric-switch
    id: key1
    pin:
      number: GPIO0
      inverted: true
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "${friendly_name} Key 2"
    icon: mdi:electric-switch
    id: key2
    pin:
      number: GPIO33
      inverted: true
    filters:
      - delayed_on_off: 50ms

packages:
  # Default device template
  default: !include ../../common/default.yaml
  esp32: !include ../../common/esp32.yaml
  buzzer: !include ../esp32/buzzer.yaml
