# Button template for my switch device
# Video: https://youtube.com/shorts/ChQIHIe7WzY

defaults:
  ignore_strapping_warning: "no"
binary_sensor:
  - platform: gpio
    name: Key ${num}
    icon: mdi:electric-switch
    id: key${num}
    pin:
      number: ${pin}
      inverted: on
      ignore_strapping_warning: ${ignore_strapping_warning}
    filters:
      - delayed_off: 50ms
