# Adds two keys of the third switch
binary_sensor:
  - platform: gpio
    name: Key 5
    icon: mdi:electric-switch
    id: key5
    pin:
      number: GPIO14
      inverted: true
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: Key 6
    icon: mdi:electric-switch
    id: key6
    pin:
      number: GPIO13
      inverted: true
    filters:
      - delayed_on_off: 50ms
