# Adds two keys of the second switch
binary_sensor:
  - platform: gpio
    name: Key 3
    icon: mdi:electric-switch
    id: key3
    pin:
      number: GPIO26
      inverted: true
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: Key 4
    icon: mdi:electric-switch
    id: key4
    pin:
      number: GPIO27
      inverted: true
    filters:
      - delayed_on_off: 50ms
